package modelo;

public enum Referencia {
	// datos
	TITULO, AUTOR, ISBN, PRECIO, PAGINAS, FORMATO, ESTADO,
	// button
	BTN_NUEVO, BTN_ALTA, BTN_BAJA, BTN_SALIR, BTN_VERDETALLES, BTN_MODIFICAR, BTN_ELIMINAR,
	// field
	FIELD_TITULO, FIELD_AUTOR, FIELD_ISBN, FIELD_PAGINAS, FIELD_PRECIO,
	// jradiobutton
	RADIOBTN_NOVEDAD, RADIOBTN_REEDICION, RADIOBTN_CARTONE, RADIOBTN_RUSTICA, RADIOBTN_DIGITAL
}
