package modelo;

public enum Referencia {
	// datos
	TITULO, AUTOR, ISBN, PRECIO, PAGINAS, FORMATO, ESTADO, TEMATICA,
	// button
	BTN_NUEVO, BTN_ALTA, BTN_BAJA, BTN_VERDETALLES, BTN_MODIFICAR, BTN_ELIMINAR, BTN_BUSCAR,
	// field
	FIELD_TITULO, FIELD_AUTOR, FIELD_ISBN, FIELD_PAGINAS, FIELD_PRECIO, FIELD_BUSQUEDAISBN,
	// jradiobutton
	RADIOBTN_NOVEDAD, RADIOBTN_REEDICION, RADIOBTN_CARTONE, RADIOBTN_RUSTICA, RADIOBTN_DIGITAL
}
